### ISSUE TITLE
Fix performance issues

### ISSUE THREAD

**Issue by fbaumgardt** [RDACollectionsWG/perseids-manifold#61]
I have confirmed that requests through the API are about 2 orders of magnitude slower than a SPARQL request on Marmotta. Needs profiling and fixing.

**Comment by fbaumgardt** [comment]
@balmas fyi

**Comment by balmas** [comment]
thanks

**Comment by fbaumgardt** [comment]
Found the culprit: https://github.com/RDACollectionsWG/perseids-manifold/blob/master/src/utils/data/ldp_db.py#L61
`result.toDataset()` is expensive but only needs to be performed once. The fixed DB function is basically as fast as pure SPARQL.

**Comment by fbaumgardt** [comment]
Further performance parameters:
- There appears to be a size limit to SPARQL queries that Marmotta can process. It's around 1,500 collections (with empty descriptions).
- Performance for collection creation drops significantly beyond 1000 collections in a single POST (posting 3x 1,000 is about as fast as 1x 1,500).

**Comment by fbaumgardt** [comment]
Mostly fixed in #65. Open new issues for additional tune-up.
