### ISSUE TITLE
update the version of the spec served at apidocs

### ISSUE THREAD

**Issue by balmas** [RDACollectionsWG/perseids-manifold#62]
the version of the spec served at the apidocs path is out of date and needs to be updated.  It also should ideally inspect the host/port and scheme under which it's running and update the JSON output of the swagger spec accordingly (basePath, host, schemes, port?). 

If it's too much work to inspect that dynamically, it should be a configuration/environment variable option.

**Comment by fbaumgardt** [comment]
Everything but `schemes` is straightforward - inspecting request.url and returning a formatted string. `schemes` may involve requesting both http and https, but I'll see if I can find a cleaner solution.

**Comment by balmas** [comment]
ok, I'm happy with whatever is easiest to implement as long as we don't have anything hard coded per deployment. Thanks!

**Comment by fbaumgardt** [comment]
See #66

**Comment by balmas** [comment]
I think I steered you slightly wrong on one part of this -- port doesn't seem to be a valid swagger property - I guess that has to go in the host? the swagger ui reports it as an error:

```
{"messages":["attribute port is unexpected"],"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"additionalProperties","message":"object instance has properties which are not allowed by the schema: [\"port\"]","schema":{"loadingURI":"#","pointer":""},"instance":{"pointer":""}}]}
```

**Comment by fbaumgardt** [comment]
That’s okay, it’ll actually be cleaner to leave domain and port in one string.
